# Generated by Django 4.2.7 on 2023-12-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0006_cart1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart1',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
