# Generated by Django 4.2.7 on 2023-12-13 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0007_cart1_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart1',
            name='quantity',
        ),
    ]
