# Generated by Django 4.2.7 on 2023-12-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0009_cart1_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart1',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
